// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAimfKbdV14iompsVE1FXwCP3mesjPMr0U',
    appId: '1:747363843777:web:a7d65675ec7c56bc8ede40',
    messagingSenderId: '747363843777',
    projectId: 'breezefoodapp',
    authDomain: 'breezefoodapp.firebaseapp.com',
    storageBucket: 'breezefoodapp.appspot.com',
    measurementId: 'G-G8KZYQT4EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0r2i_dWEC6Hbj6zfqJzAjetHvswwMbnQ',
    appId: '1:747363843777:android:ff46008b54659ff78ede40',
    messagingSenderId: '747363843777',
    projectId: 'breezefoodapp',
    storageBucket: 'breezefoodapp.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC5-uQivSo9m365cl8sissNYUs63ytNMk',
    appId: '1:747363843777:ios:1a65a5240b6d09778ede40',
    messagingSenderId: '747363843777',
    projectId: 'breezefoodapp',
    storageBucket: 'breezefoodapp.appspot.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAimfKbdV14iompsVE1FXwCP3mesjPMr0U',
    appId: '1:747363843777:web:1aab27ee06fd9b478ede40',
    messagingSenderId: '747363843777',
    projectId: 'breezefoodapp',
    authDomain: 'breezefoodapp.firebaseapp.com',
    storageBucket: 'breezefoodapp.appspot.com',
    measurementId: 'G-Q1EB8K25WG',
  );
}
